'use client';

import { useState, useEffect } from 'react';
import {
    Search,
    Bug,
    AlertTriangle,
    AlertCircle,
    Info,
    ArrowDown,
    RefreshCw,
    Sparkles,
    FileCode,
    Plus,
    ExternalLink,
    Shield,
    Zap,
    BarChart3,
} from 'lucide-react';
import toast from 'react-hot-toast';
import { useSettings, useConnectedRepos, useStats, useActivity } from '../lib/store';
import type { ScannedIssue, ScanResult } from '../lib/types';

export default function IssueScannerPage() {
    const { settings } = useSettings();
    const { repos } = useConnectedRepos();
    const { incrementStat } = useStats();
    const { addActivity } = useActivity();
    const [selectedRepo, setSelectedRepo] = useState('');
    const [scanning, setScanning] = useState(false);
    const [scanResult, setScanResult] = useState<ScanResult | null>(null);
    const [creatingIssue, setCreatingIssue] = useState<string | null>(null);
    const [mounted, setMounted] = useState(false);

    useEffect(() => setMounted(true), []);

    const runScan = async (repoFullName: string) => {
        if (!settings.githubToken || !settings.geminiApiKey) {
            toast.error('Please set both GitHub token and Gemini API key in Settings');
            return;
        }
        setSelectedRepo(repoFullName);
        setScanning(true);
        setScanResult(null);

        try {
            const res = await fetch('/api/ai/scan', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    githubToken: settings.githubToken,
                    geminiApiKey: settings.geminiApiKey,
                    owner: repoFullName.split('/')[0],
                    repo: repoFullName.split('/')[1],
                }),
            });

            if (res.ok) {
                const data = await res.json();
                setScanResult({ ...data, repoName: repoFullName });
                toast.success(`Scan complete! Found ${data.totalIssues} issues.`);
            } else {
                const err = await res.json();
                toast.error(err.error || 'Scan failed');
            }
        } catch {
            toast.error('Scan failed');
        }
        setScanning(false);
    };

    const createGitHubIssue = async (issue: ScannedIssue) => {
        if (!settings.githubToken) return;
        setCreatingIssue(issue.id);

        try {
            const [owner, repo] = selectedRepo.split('/');
            const body = `## ${issue.category.toUpperCase()}: ${issue.title}

**Severity:** ${issue.severity}
**File:** \`${issue.file}\` (L${issue.lineStart}-L${issue.lineEnd})

### Description
${issue.description}

### Suggested Fix
\`\`\`
${issue.suggestedFix}
\`\`\`

---
*🤖 This issue was auto-generated by GitAgent AI*`;

            const res = await fetch('/api/github/issues', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'x-github-token': settings.githubToken,
                },
                body: JSON.stringify({
                    owner,
                    repo,
                    title: `[${issue.severity.toUpperCase()}] ${issue.title}`,
                    body,
                    labels: [issue.severity, issue.category, 'ai-generated'],
                }),
            });

            if (res.ok) {
                incrementStat('issuesFixed');
                addActivity({
                    type: 'issue-created',
                    title: `Issue Created: ${issue.title}`,
                    description: `Created in ${selectedRepo}`,
                    repo: selectedRepo,
                    status: 'success',
                });
                toast.success('Issue created on GitHub!');
            } else {
                toast.error('Failed to create issue');
            }
        } catch {
            toast.error('Failed to create issue');
        }
        setCreatingIssue(null);
    };

    const getSeverityConfig = (severity: string) => {
        const configs: Record<string, { color: string; bg: string; icon: React.ComponentType<{ size?: number; style?: React.CSSProperties }> }> = {
            critical: { color: 'var(--error)', bg: 'rgba(255,107,107,0.08)', icon: AlertTriangle },
            high: { color: '#ff9f43', bg: 'rgba(255,159,67,0.08)', icon: AlertCircle },
            medium: { color: 'var(--warning)', bg: 'rgba(253,203,110,0.08)', icon: Info },
            low: { color: 'var(--info)', bg: 'rgba(116,185,255,0.08)', icon: Info },
        };
        return configs[severity] || configs.medium;
    };

    if (!mounted) return null;

    return (
        <div style={{ maxWidth: '1200px' }}>
            {/* Repo Selection */}
            <div className="glass-card animate-fade-in" style={{ padding: '24px', marginBottom: '24px' }}>
                <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Search size={18} style={{ color: 'var(--accent-secondary)' }} />
                    Select Repository to Scan
                </h3>
                {repos.length > 0 ? (
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
                        {repos.map((repo) => (
                            <button
                                key={repo}
                                onClick={() => runScan(repo)}
                                className={selectedRepo === repo ? 'btn-gradient' : 'btn-secondary'}
                                disabled={scanning}
                                style={{ fontSize: '13px' }}
                            >
                                {scanning && selectedRepo === repo ? (
                                    <RefreshCw size={14} className="animate-spin-slow" />
                                ) : (
                                    <Bug size={14} />
                                )}
                                {repo}
                            </button>
                        ))}
                    </div>
                ) : (
                    <p style={{ color: 'var(--text-muted)', fontSize: '14px' }}>
                        No repositories connected. <a href="/repositories" style={{ color: 'var(--accent-secondary)' }}>Add one first</a>.
                    </p>
                )}
            </div>

            {/* Scanning Animation */}
            {scanning && (
                <div className="glass-card animate-fade-in" style={{ padding: '48px', textAlign: 'center' }}>
                    <Sparkles size={48} style={{ color: 'var(--accent-secondary)', marginBottom: '16px' }} className="animate-float" />
                    <p style={{ fontWeight: 600, fontSize: '18px' }}>Scanning Repository...</p>
                    <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '8px' }}>
                        AI is analyzing your code for bugs, security issues, and improvements
                    </p>
                    <div style={{ display: 'flex', justifyContent: 'center', gap: '24px', marginTop: '24px' }}>
                        {['Security', 'Performance', 'Bugs', 'Quality'].map((label, i) => (
                            <div key={label} style={{ display: 'flex', alignItems: 'center', gap: '6px', opacity: 0, animation: 'fadeIn 0.5s ease forwards', animationDelay: `${i * 0.3}s` }}>
                                <div className="skeleton" style={{ width: '12px', height: '12px', borderRadius: '50%' }} />
                                <span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>{label}</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Scan Results */}
            {scanResult && !scanning && (
                <>
                    {/* Summary Cards */}
                    <div
                        className="animate-fade-in"
                        style={{
                            display: 'grid',
                            gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
                            gap: '12px',
                            marginBottom: '24px',
                        }}
                    >
                        {[
                            { label: 'Total Issues', value: scanResult.totalIssues, color: 'var(--text-primary)', icon: BarChart3 },
                            { label: 'Critical', value: scanResult.criticalCount, color: 'var(--error)', icon: AlertTriangle },
                            { label: 'High', value: scanResult.highCount, color: '#ff9f43', icon: AlertCircle },
                            { label: 'Medium', value: scanResult.mediumCount, color: 'var(--warning)', icon: Info },
                            { label: 'Low', value: scanResult.lowCount, color: 'var(--info)', icon: Shield },
                        ].map((stat) => {
                            const Icon = stat.icon;
                            return (
                                <div key={stat.label} className="glass-card" style={{ padding: '20px', textAlign: 'center' }}>
                                    <Icon size={20} style={{ color: stat.color, marginBottom: '8px' }} />
                                    <div style={{ fontSize: '28px', fontWeight: 700, color: stat.color }}>{stat.value}</div>
                                    <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px' }}>{stat.label}</div>
                                </div>
                            );
                        })}
                    </div>

                    {/* Issue List */}
                    <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px' }}>
                        Found Issues
                    </h3>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                        {scanResult.issues.map((issue, i) => {
                            const config = getSeverityConfig(issue.severity);
                            const Icon = config.icon;
                            return (
                                <div
                                    key={issue.id}
                                    className="glass-card animate-fade-in"
                                    style={{
                                        padding: '20px',
                                        borderLeft: `3px solid ${config.color}`,
                                        animationDelay: `${i * 0.05}s`,
                                        opacity: 0,
                                        animationFillMode: 'forwards',
                                    }}
                                >
                                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                            <Icon size={18} style={{ color: config.color }} />
                                            <span style={{ fontWeight: 600, fontSize: '14px' }}>{issue.title}</span>
                                            <span className={`badge badge-${issue.severity === 'critical' ? 'error' : issue.severity === 'high' ? 'warning' : issue.severity === 'medium' ? 'warning' : 'info'}`}>
                                                {issue.severity}
                                            </span>
                                            <span className="badge badge-neutral">{issue.category}</span>
                                        </div>
                                        <button
                                            className="btn-gradient"
                                            style={{ padding: '6px 14px', fontSize: '12px' }}
                                            onClick={() => createGitHubIssue(issue)}
                                            disabled={creatingIssue === issue.id}
                                        >
                                            {creatingIssue === issue.id ? (
                                                <RefreshCw size={12} className="animate-spin-slow" />
                                            ) : (
                                                <Plus size={12} />
                                            )}
                                            Create Issue
                                        </button>
                                    </div>
                                    <p style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: '1.6', marginBottom: '8px' }}>
                                        {issue.description}
                                    </p>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', fontSize: '12px', color: 'var(--text-muted)' }}>
                                        <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                            <FileCode size={12} /> {issue.file}
                                        </span>
                                        <span>L{issue.lineStart}–L{issue.lineEnd}</span>
                                    </div>
                                    {issue.suggestedFix && (
                                        <div className="code-block" style={{ marginTop: '12px', fontSize: '12px' }}>
                                            <div style={{ color: 'var(--text-muted)', marginBottom: '6px', fontSize: '11px' }}>
                                                💡 Suggested Fix:
                                            </div>
                                            <code style={{ color: 'var(--success)', whiteSpace: 'pre-wrap' }}>
                                                {issue.suggestedFix}
                                            </code>
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </>
            )}
        </div>
    );
}
