import { NextRequest, NextResponse } from 'next/server';
import { fetchFileContent, createBranch, commitFile, createPullRequest, createOctokit } from '../../../lib/github';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { githubToken, provider, apiKey, owner, repo, issueNumber, issueTitle, issueBody, targetFile, suggestedFix } = body;

        if (!githubToken || !owner || !repo || !issueNumber) {
            return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
        }
        if (!apiKey) {
            return NextResponse.json({ error: 'Missing AI API key' }, { status: 400 });
        }

        // Step 1: Fetch current file content
        let fileContent = '';
        try {
            fileContent = await fetchFileContent(githubToken, owner, repo, targetFile);
        } catch {
            return NextResponse.json({ error: `Could not fetch file: ${targetFile}` }, { status: 400 });
        }

        // Step 2: Ask AI to generate the fix
        const prompt = `You are an Autonomous AI Agent solving a GitHub issue.

Repository: ${owner}/${repo}
Issue #${issueNumber}: ${issueTitle}
Description: ${issueBody}
${suggestedFix ? `Suggested fix: ${suggestedFix}` : ''}

Here is the current content of \`${targetFile}\`:
\`\`\`
${fileContent.substring(0, 15000)}
\`\`\`

Generate the complete, updated content for \`${targetFile}\` that fixes this issue professionally.
Make the minimal necessary changes to fix the issue. Be precise and production-quality.
Respond ONLY with the raw file content. No markdown blocks. No explanations.`;

        let newContent = '';

        if (provider === 'gemini') {
            const { GoogleGenAI } = await import('@google/genai');
            const ai = new GoogleGenAI({ apiKey });
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: prompt,
            });
            newContent = response.text || fileContent;
        } else {
            const OpenAI = (await import('openai')).default;
            const openai = new OpenAI({ apiKey });
            const response = await openai.chat.completions.create({
                model: 'gpt-4o',
                messages: [{ role: 'user', content: prompt }],
            });
            newContent = response.choices[0]?.message?.content || fileContent;
        }

        // Cleanup
        newContent = newContent.replace(/^```[a-z]*\n/i, '').replace(/\n```$/i, '').trim() + '\n';

        // Step 3: Create branch
        const branchName = `auto-solve/issue-${issueNumber}-${Math.random().toString(36).substring(2, 8)}`;
        await createBranch(githubToken, owner, repo, branchName, 'main');

        // Step 4: Commit fix
        await commitFile(
            githubToken, owner, repo, targetFile,
            `fix: resolve #${issueNumber} — ${issueTitle}`,
            newContent, branchName
        );

        // Step 5: Open PR
        const prData = await createPullRequest(
            githubToken, owner, repo,
            `🤖 Fix #${issueNumber}: ${issueTitle}`,
            `## Automated Fix for #${issueNumber}\n\n### Issue\n${issueBody}\n\n### Changes\n- Fixed \`${targetFile}\`\n\nCloses #${issueNumber}\n\n---\n*🤖 This PR was autonomously generated by GitAgent AI to solve the issue.*`,
            branchName,
            'main'
        );

        // Step 6: Comment on the issue that it's being fixed
        const octokit = createOctokit(githubToken);
        await octokit.rest.issues.createComment({
            owner, repo,
            issue_number: issueNumber,
            body: `🤖 **GitAgent AI** has created a fix for this issue!\n\n**PR:** #${prData.number} — [View PR](${prData.html_url})\n\nThe fix has been automatically generated and submitted for review.`,
        });

        // Step 7: Close the issue
        await octokit.rest.issues.update({
            owner, repo,
            issue_number: issueNumber,
            state: 'closed',
            state_reason: 'completed',
        });

        return NextResponse.json({
            success: true,
            prNumber: prData.number,
            prUrl: prData.html_url,
            issueClosed: true,
        });
    } catch (error: any) {
        return NextResponse.json({ error: error.message || 'Auto-solve failed' }, { status: 500 });
    }
}
