import { NextRequest, NextResponse } from 'next/server';
import { createOctokit, fetchUserProfile } from '../../../lib/github';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { githubToken, action, badgeId, provider, apiKey } = body;

        if (!githubToken) {
            return NextResponse.json({ error: 'Missing GitHub token' }, { status: 400 });
        }

        const octokit = createOctokit(githubToken);
        const user = await fetchUserProfile(githubToken);
        const results: string[] = [];

        if (action === 'auto_earn') {
            // Badge-specific automation
            if (badgeId === 'first-repo' || badgeId === 'repo-collector' || badgeId === 'repo-master') {
                // Create a new repository
                const repoName = `auto-project-${Math.random().toString(36).substring(2, 8)}`;
                const { data: newRepo } = await octokit.rest.repos.createForAuthenticatedUser({
                    name: repoName,
                    description: '🤖 Automatically generated by GitAgent to build portfolio',
                    auto_init: true,
                    private: false,
                });
                results.push(`✅ Created repository: ${newRepo.full_name}`);

                // Add a README with useful content if we have AI
                if (apiKey) {
                    let readmeContent = `# ${repoName}\n\nAuto-generated project.`;
                    try {
                        if (provider === 'gemini') {
                            const { GoogleGenAI } = await import('@google/genai');
                            const ai = new GoogleGenAI({ apiKey });
                            const response = await ai.models.generateContent({
                                model: 'gemini-1.5-flash',
                                contents: `Generate a professional README.md for a new open-source project called "${repoName}". Include: title, description, features, installation, usage, contributing guidelines, license section. Make it look impressive. Return just the markdown content.`,
                            });
                            readmeContent = response.text || readmeContent;
                        } else {
                            const OpenAI = (await import('openai')).default;
                            const openai = new OpenAI({ apiKey });
                            const resp = await openai.chat.completions.create({
                                model: 'gpt-4o-mini',
                                messages: [{ role: 'user', content: `Generate a professional README.md for a new open-source project called "${repoName}". Include: title, description, features, installation, usage, contributing guidelines, license section. Make it look impressive. Return just the markdown content.` }],
                            });
                            readmeContent = resp.choices[0]?.message?.content || readmeContent;
                        }
                    } catch { /* use default */ }

                    // Wait for repo initialization
                    await new Promise(resolve => setTimeout(resolve, 2000));

                    try {
                        // Get current README sha
                        const { data: currentFile } = await octokit.rest.repos.getContent({
                            owner: user.login, repo: repoName, path: 'README.md',
                        });
                        const sha = !Array.isArray(currentFile) && currentFile.type === 'file' ? currentFile.sha : undefined;

                        await octokit.rest.repos.createOrUpdateFileContents({
                            owner: user.login, repo: repoName, path: 'README.md',
                            message: 'docs: add comprehensive README',
                            content: Buffer.from(readmeContent).toString('base64'),
                            sha,
                        });
                        results.push('✅ Added AI-generated README.md');
                    } catch { /* ignore */ }
                }
            }

            if (badgeId === 'snippet-master') {
                // Create a gist
                const { data: gist } = await octokit.rest.gists.create({
                    description: '🤖 Useful code snippet by GitAgent',
                    public: true,
                    files: {
                        'useful-utils.js': {
                            content: `// Useful JavaScript Utility Functions\n// Auto-generated by GitAgent\n\n/**\n * Debounce function calls\n * @param {Function} func - Function to debounce\n * @param {number} wait - Wait time in ms\n */\nexport function debounce(func, wait) {\n  let timeout;\n  return function executedFunction(...args) {\n    clearTimeout(timeout);\n    timeout = setTimeout(() => func.apply(this, args), wait);\n  };\n}\n\n/**\n * Deep clone an object\n * @param {Object} obj - Object to clone\n */\nexport function deepClone(obj) {\n  return JSON.parse(JSON.stringify(obj));\n}\n\n/**\n * Format bytes to human readable string\n * @param {number} bytes\n */\nexport function formatBytes(bytes, decimals = 2) {\n  if (bytes === 0) return '0 Bytes';\n  const k = 1024;\n  const sizes = ['Bytes', 'KB', 'MB', 'GB'];\n  const i = Math.floor(Math.log(bytes) / Math.log(k));\n  return parseFloat((bytes / Math.pow(k, i)).toFixed(decimals)) + ' ' + sizes[i];\n}\n`,
                        },
                    },
                });
                results.push(`✅ Created public gist: ${gist.html_url}`);
            }

            if (badgeId === 'bug-reporter' || badgeId === 'issue-hunter') {
                // Create an issue on user's own repo
                const { data: repos } = await octokit.rest.repos.listForAuthenticatedUser({ sort: 'updated', per_page: 5 });
                const ownRepo = repos.find((r: any) => !r.fork && r.owner.login === user.login);
                if (ownRepo) {
                    const { data: issue } = await octokit.rest.issues.create({
                        owner: user.login,
                        repo: ownRepo.name,
                        title: '📋 Code improvement tracker',
                        body: `## Improvement Ideas\n\nThis issue tracks potential improvements:\n\n- [ ] Add comprehensive error handling\n- [ ] Improve test coverage\n- [ ] Add TypeScript types\n- [ ] Performance optimizations\n\n---\n*🤖 Auto-created by GitAgent*`,
                        labels: ['enhancement', 'good first issue'],
                    });
                    results.push(`✅ Created issue #${issue.number} on ${ownRepo.full_name}`);
                }
            }

            if (badgeId === 'first-pr' || badgeId === 'pr-machine') {
                // Create a PR on user's own repo
                const { data: repos } = await octokit.rest.repos.listForAuthenticatedUser({ sort: 'updated', per_page: 10 });
                const ownRepo = repos.find((r: any) => !r.fork && r.owner.login === user.login);
                if (ownRepo) {
                    const branchName = `auto-improve-${Math.random().toString(36).substring(2, 8)}`;
                    try {
                        // Get default branch SHA
                        const { data: ref } = await octokit.rest.git.getRef({
                            owner: user.login, repo: ownRepo.name, ref: `heads/${ownRepo.default_branch}`,
                        });

                        // Create branch
                        await octokit.rest.git.createRef({
                            owner: user.login, repo: ownRepo.name,
                            ref: `refs/heads/${branchName}`,
                            sha: ref.object.sha,
                        });

                        // Add a file
                        await octokit.rest.repos.createOrUpdateFileContents({
                            owner: user.login, repo: ownRepo.name,
                            path: '.github/CONTRIBUTING.md',
                            message: 'docs: add contributing guidelines',
                            content: Buffer.from(`# Contributing to ${ownRepo.name}\n\nThank you for your interest in contributing!\n\n## How to Contribute\n\n1. Fork the repository\n2. Create a feature branch\n3. Make your changes\n4. Submit a pull request\n\n## Code of Conduct\n\nPlease be respectful and constructive.\n`).toString('base64'),
                            branch: branchName,
                        });

                        // Open PR
                        const { data: pr } = await octokit.rest.pulls.create({
                            owner: user.login, repo: ownRepo.name,
                            title: '📝 Add contributing guidelines',
                            body: `## Changes\n- Added CONTRIBUTING.md with guidelines for contributors\n\n---\n*🤖 Auto-generated by GitAgent*`,
                            head: branchName,
                            base: ownRepo.default_branch,
                        });
                        results.push(`✅ Created PR #${pr.number} on ${ownRepo.full_name}: ${pr.html_url}`);
                    } catch (err: any) {
                        results.push(`⚠️ PR creation: ${err.message}`);
                    }
                }
            }

            if (results.length === 0) {
                results.push('ℹ️ This badge requires organic GitHub activity that cannot be directly automated.');
            }

            return NextResponse.json({ success: true, results });
        }

        return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
    } catch (error: any) {
        return NextResponse.json({ error: error.message || 'Auto-badge failed' }, { status: 500 });
    }
}
